# config.yaml

model: zai-org/GLM-4.5-Air-FP8 # 106B-A12B
host: "0.0.0.0"
port: 8080
uvicorn-log-level: "info"
tensor-parallel-size: 4
gpu-memory-utilization: 0.8
max-model-len: 32768
max-num-seqs: 32 # 128
override-generation-config: '{ "max_new_tokens": 16384 }'
seed: 42
enable_prefix_caching: true
max-num-batched-tokens: 16384