# config.yaml

model: zai-org/GLM-4.5-Air-FP8 # 106B-A12B
host: "0.0.0.0"
port: 8080
uvicorn-log-level: "info"
tensor-parallel-size: 4
gpu-memory-utilization: 0.9
max-model-len: 32768
max-num-seqs: 128 # 128
override-generation-config: '{ "temperature": 0.6, "top_p": 0.8, "top_k": 40, "max_new_tokens": 16384 }'
seed: 42
enable_prefix_caching: true
max-num-batched-tokens: 32768