PLANNER_BASE_URL: "http://172.28.45.172:8080/v1"
RESPONDER_BASE_URL: "http://172.28.35.12:8080/v1" 
EVALUATOR_BASE_URL: "http://172.28.45.172:8080/v1"

PLANNER_MODEL: "Qwen/Qwen3-Next-80B-A3B-Instruct" # w/o prefix caching
RESPONDER_MODEL: "openai/gpt-oss-120b" # w/o prefix caching 
EVALUATOR_MODEL: "Qwen/Qwen3-Next-80B-A3B-Instruct" # w/ prefix caching
